services:
  - type: web
    name: backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: snapdevproject
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: "https://demo-project-repo.onrender.com,*"
  - type: web
    name: frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/dist"
    routes:
      - type: rewrite
        source: /api/:path*
        destination: "https://demo-project-repo-backend.onrender.com/:path*"
    envVars:
      - key: VITE_API_URL
        value: "https://demo-project-repo-backend.onrender.com"